### ISSUE TITLE
L5rcm Error

### ISSUE THREAD

**Issue by JThoreck** [OpenNingia/l5r-character-manager-3#256] opened 2014-10-23 04:33 UTC
I downloaded decompression program, and I was finally able to install the L5rcm. However, when I try to launch it, it says "l5rcm Error". The options I am given are to either Open Console or Terminate. If I open the console I see this: 

10/22/14 9:28:40.708 PM l5rcm[401]: Traceback (most recent call last):
10/22/14 9:28:40.708 PM l5rcm[401]:   File "/Users/josephthoreck/Desktop/l5rcm.app/Contents/Resources/__boot__.py", line 351, in <module>
10/22/14 9:28:40.708 PM l5rcm[401]:     _run()
10/22/14 9:28:40.709 PM l5rcm[401]:   File "/Users/josephthoreck/Desktop/l5rcm.app/Contents/Resources/__boot__.py", line 336, in _run
10/22/14 9:28:40.709 PM l5rcm[401]:     exec(compile(source, path, 'exec'), globals(), globals())
10/22/14 9:28:40.709 PM l5rcm[401]:   File "/Users/josephthoreck/Desktop/l5rcm.app/Contents/Resources/l5rcm.py", line 21, in <module>
10/22/14 9:28:40.709 PM l5rcm[401]:     import rules
10/22/14 9:28:40.709 PM l5rcm[401]:   File "rules/__init__.pyc", line 18, in <module>
10/22/14 9:28:40.709 PM l5rcm[401]:   File "models/__init__.pyc", line 17, in <module>
10/22/14 9:28:40.709 PM l5rcm[401]:   File "models/advances.pyc", line 17, in <module>
10/22/14 9:28:40.709 PM l5rcm[401]:   File "PySide/QtCore.pyc", line 14, in <module>
10/22/14 9:28:40.709 PM l5rcm[401]:   File "PySide/QtCore.pyc", line 10, in __load
10/22/14 9:28:40.709 PM l5rcm[401]: ImportError: dlopen(/Users/josephthoreck/Desktop/l5rcm.app/Contents/Resources/lib/python2.7/lib-dynload/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside-python2.7.1.2.dylib
10/22/14 9:28:40.710 PM l5rcm[401]:   Referenced from: /Users/josephthoreck/Desktop/l5rcm.app/Contents/Resources/lib/python2.7/lib-dynload/PySide/QtCore.so
10/22/14 9:28:40.710 PM l5rcm[401]:   Reason: image not found
10/22/14 9:28:40.719 PM l5rcm[401]: l5rcm Error
10/22/14 9:28:40.720 PM l5rcm[401]: 2014-10-22 21:28:40.719 l5rcm[401:18465] l5rcm Error
10/22/14 9:28:47.620 PM SystemUIServer[201]: Attempt to use XPC with a MachService that has HideUntilCheckIn set. This will result in unpredictable behavior: com.apple.backupd.status.xpc
10/22/14 9:29:09.950 PM mdworker[412]: code validation failed in the process of getting signing information: Error Domain=NSOSStatusErrorDomain Code=-67062 "The operation couldn’t be completed. (OSStatus error -67062.)"
10/22/14 9:29:39.935 PM mdworker[413]: code validation failed in the process of getting signing information: Error Domain=NSOSStatusErrorDomain Code=-67062 "The operation couldn’t be completed. (OSStatus error -67062.)"
10/22/14 9:30:15.258 PM mds[32]: (Volume.Normal:2464) volume:0x7fd262828000 ********** Bootstrapped Creating a default store:0 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/firmwaresyncd.wQXtxE

Please help!

**Comment by OpenNingia** [comment] 2015-08-17 20:19
duplicate of #254

**Closed by OpenNingia** 2015-08-17 20:19 UTC
Labels: duplicate, help wanted, macosx
